apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-9.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-9.4
  template:
    metadata:
      labels:
        app: postgres-9.4
    spec:
      containers:
      - name: postgres-9.4
        image: postgres:9.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
