apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-alpine
  template:
    metadata:
      labels:
        app: redis-alpine
    spec:
      containers:
      - name: redis-alpine
        image: redis:alpine
        ports:
        - containerPort: 6379
