apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: dockersamples/examplevotingapp_vote:before
        ports:
        - containerPort: 80
        env:
        - name: OPTION_A
          value: Cats
        - name: OPTION_B
          value: Dogs
        - name: REDIS
          value: redis-alpine
